global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi'
   
    static_configs:
      - targets: ['http://127.0.0.1:37547/']  # Replace with your NodePort
