apiVersion: v1
kind: Service
metadata:
  name: fastapi-svc
  namespace: fastapi
spec:
  type: LoadBalancer
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 9009
      targetPort: 9009

